language: node_js
node_js:
    - "0.12"
    - "0.11"
    - "0.10"
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb
  - rethinkdb --deamon
